<a href="https://colab.research.google.com/github/sanaullah-developer/tensorflow_practice/blob/main/linear_algebra_and_einsum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
t1=tf.constant([
    [1,2],
    [3,4]
])
t2=tf.constant([
    [5,6],
    [7,8]
])

In [5]:
# linalg is a module in tensorflow mainly related to linear algebra
print(tf.linalg.matmul(t1,t2)) # matmul is used for matrix multiplication
print(t1@t2)# we can also use the "@" between matrix for matrix multiplication

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [8]:
print("matrix before transpose", t1)
print(" matrix after transpose", tf.transpose(t1))

matrix before transpose tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
 matrix after transpose tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [9]:
print(tf.linalg.adjoint(t1))

tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [14]:
print("dot product in normal way",t1*t2)
print("dot product in einsum way",tf.einsum("ij,ij-> ij",t1,t2)) #dot product

dot product in normal way tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
dot product in einsum way tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [17]:
print("cross product in normal way",t1@t2)
print("cross product in einsum way",tf.einsum("ij,jk->ik",t1,t2))

cross product in normal way tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
cross product in einsum way tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [19]:
print("transpose in normal way",tf.transpose(t1))
print("transpose in einsum way",tf.einsum("ij->ji",t1))

transpose in normal way tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
transpose in einsum way tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
