<a href="https://colab.research.google.com/github/sanaullah-developer/tensorflow_practice/blob/main/math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor=tf.constant([1,2,3,-4,-5,-6])
print(tensor)

tf.Tensor([ 1  2  3 -4 -5 -6], shape=(6,), dtype=int32)


In [3]:
print(tf.math.abs(tensor)) # the abs method convert the negative number into positive

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [8]:
print(tf.sqrt(25.0))

tf.Tensor(5.0, shape=(), dtype=float32)


In [11]:
squared_tensor=tf.constant([4.,9,16,25])
unsquared_tensor=tf.sqrt(squared_tensor)
print(unsquared_tensor)

tf.Tensor([2. 3. 4. 5.], shape=(4,), dtype=float32)


In [10]:
t1=tf.constant([1,2,3,4,5])
t2=tf.constant([6,7,8,9,0])
print(tf.add(t1,t2))

tf.Tensor([ 7  9 11 13  5], shape=(5,), dtype=int32)


In [12]:
print(tf.subtract(t1,t2))

tf.Tensor([-5 -5 -5 -5  5], shape=(5,), dtype=int32)


In [13]:
print(tf.multiply(t1,t2))

tf.Tensor([ 6 14 24 36  0], shape=(5,), dtype=int32)


In [14]:
print(tf.divide(t1,t2))

tf.Tensor([0.16666667 0.28571429 0.375      0.44444444        inf], shape=(5,), dtype=float64)


In [15]:
#if both matrix are not of same size then broadcasting will happen
t3=tf.constant([3])
print(tf.add(t1,t3)) # 3 will be added to every element in t1 and not just to first element

tf.Tensor([4 5 6 7 8], shape=(5,), dtype=int32)


In [17]:
t4=tf.constant([[3],[4],[5]])
print(tf.add(t1,t4)) # in this broadcasting will happen in such manner that the the t1 which has one dimension will strech to two dimension
# copy the same element in row 1 to make row 2 and row 3 so that can be added so 3 will be added to first row and 4 to second and 5 to third

tf.Tensor(
[[ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]], shape=(3, 5), dtype=int32)


In [18]:
print(tf.math.pow(t1, 3))

tf.Tensor([  1   8  27  64 125], shape=(5,), dtype=int32)


In [19]:
ten_2d=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
])

In [20]:
print(tf.math.reduce_sum(ten_2d))

tf.Tensor(42, shape=(), dtype=int32)


In [21]:
print(tf.math.reduce_mean(ten_2d))

tf.Tensor(3, shape=(), dtype=int32)


In [25]:
tf.math.top_k(ten_2d,k=2)

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 3],
       [5, 4],
       [6, 5]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 2],
       [3, 2],
       [3, 2]], dtype=int32)>)

AttributeError: module 'tensorflow._api.v2.math' has no attribute 'top_min'