<a href="https://colab.research.google.com/github/sanaullah-developer/tensorflow_practice/blob/main/randomization_and_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor=tf.eye(4)

In [ ]:
print(tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [ ]:

tensor.shape

TensorShape([4, 4])

In [ ]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
print(tf.size(tensor))

tf.Tensor(16, shape=(), dtype=int32)


In [ ]:
random_normal_tensor=tf.random.normal((3,4),5)

In [ ]:
print(random_normal_tensor)

tf.Tensor(
[[4.287406  6.409255  5.1114144 5.1585813]
 [4.725001  3.1851594 3.5601807 6.3544126]
 [6.0524116 4.6350994 6.661827  3.1906292]], shape=(3, 4), dtype=float32)


In [ ]:
random_uniform_tensor=tf.random.uniform((3,4),100,500,tf.dtypes.int32)
print(random_uniform_tensor)

tf.Tensor(
[[401 480 477 406]
 [412 172 415 432]
 [253 194 297 308]], shape=(3, 4), dtype=int32)


In [20]:
print(random_uniform_tensor[:,:])

tf.Tensor(
[[401 480 477 406]
 [412 172 415 432]
 [253 194 297 308]], shape=(3, 4), dtype=int32)


In [23]:
print(random_uniform_tensor[1:3,:])

tf.Tensor(
[[412 172 415 432]
 [253 194 297 308]], shape=(2, 4), dtype=int32)


In [24]:
print(random_uniform_tensor[:,2:4])

tf.Tensor(
[[477 406]
 [415 432]
 [297 308]], shape=(3, 2), dtype=int32)
