<a href="https://colab.research.google.com/github/sanaullah-developer/tensorflow_practice/blob/main/tensor_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np


In [ ]:
A=tf.constant([
    [1,3,4,5],
    [5,6,7,8],
    [2,4,6,1]
])

In [ ]:
#expanding dimension of a matrix
B=tf.expand_dims(A, axis=0)
print(B.shape)

(1, 3, 4)


In [ ]:
print(B)

tf.Tensor(
[[[1 3 4 5]
  [5 6 7 8]
  [2 4 6 1]]], shape=(1, 3, 4), dtype=int32)


In [ ]:
#squeezing the dimension but this work where we are removing the dimension having value 0
C=tf.squeeze(B,axis=0)
print(C)

tf.Tensor(
[[1 3 4 5]
 [5 6 7 8]
 [2 4 6 1]], shape=(3, 4), dtype=int32)


In [ ]:
D=tf.squeeze(A,axis=0) #this gives us error because the dimension that we are removing has value 3 not 1

InvalidArgumentError: {{function_node __wrapped__Squeeze_device_/job:localhost/replica:0/task:0/device:CPU:0}} Can not squeeze dim[0], expected a dimension of 1, got 3 [Op:Squeeze] name: 

In [ ]:
#we can also reshape the matirix into another dimension but the element should fit in the new dimension completly
#if we have dimession of shape (4,2) we can convert it into (2,4) or into (8)
reshaped=tf.reshape(A,[6,2])
print(reshaped)

tf.Tensor(
[[1 3]
 [4 5]
 [5 6]
 [7 8]
 [2 4]
 [6 1]], shape=(6, 2), dtype=int32)


In [ ]:
#we can also convert it into higher dimenstion
reshape_higher=tf.reshape(A,[2,3,2])
print(reshape_higher)

tf.Tensor(
[[[1 3]
  [4 5]
  [5 6]]

 [[7 8]
  [2 4]
  [6 1]]], shape=(2, 3, 2), dtype=int32)


In [ ]:
#we can also do concatination of matrix of same size
t1=[[1,2,3],
    [4,5,6]]
t2=[[7,8,9],
    [10,11,12]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1,t2],axis=0)

#we have to note that when we concat with axis 0, in resultant
#matrix shape the axis 0 of t1 and t2 will be added and axis 1
#remain same as it is in t1 and t2 and not added
#t1=(2,3), t2=(2,3)  result=(4,3)

(2, 3)
(2, 3)


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 1,], [3, 2]])
#[[1, 1,], [2, 2]]-> 1 row above,1 below,2 to right,2 to left
tf.pad(t, paddings, "CONSTANT")

<tf.Tensor: shape=(4, 8), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 3, 0, 0],
       [0, 0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
tf.pad(t,paddings,"CONSTANT",constant_values=5)

<tf.Tensor: shape=(4, 8), dtype=int32, numpy=
array([[5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 1, 2, 3, 5, 5],
       [5, 5, 5, 4, 5, 6, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5]], dtype=int32)>

In [ ]:
#gather method takes element from different indices and combine into a single matrix
params = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])


tf.gather(params, [0,2], axis=0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [7, 8, 9]], dtype=int32)>

In [ ]:
#tf.gather_nd extracts elements or slices from a tensor using multi-dimensional indices.
params = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
tf.gather_nd(params, [[0, 1],
                       [2, 0]])


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 7], dtype=int32)>

In [ ]:
#normally matrix are ractangular but we can make non ractangular matrix with ragged function
non_uniform_matrix=[[1,2,0],
                    [3,],
                    [1,2,3,4,5],
                    [2,3]]
tensor_ragged=tf.ragged.constant(non_uniform_matrix)
print(non_uniform_matrix)

[[1, 2, 0], [3], [1, 2, 3, 4, 5], [2, 3]]
