<a href="https://colab.research.google.com/github/sanaullah-developer/tensorflow_practice/blob/main/tensor_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_0D=tf.constant(5)

In [ ]:
print(tensor_0D)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
tensor_1D=tf.constant([1,2,3,4])
print(tensor_1D)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [ ]:
tensor_2D=tf.constant([
    [1,2,3,4],
    [2,3,4,5],
    [5,6,7,8]
])
print(tensor_2D)

tf.Tensor(
[[1 2 3 4]
 [2 3 4 5]
 [5 6 7 8]], shape=(3, 4), dtype=int32)


In [ ]:
tensor_3D=tf.constant([
    [[1,2,3,4],
    [2,4,4,5],
    [5,6,7,9]],
    [[1,2,3,4],
    [2,3,4,5],
    [0,6,9,8]],
    [[1,2,1,4],
    [2,4,4,5],
    [5,6,7,3]]
])
print(tensor_3D)

tf.Tensor(
[[[1 2 3 4]
  [2 4 4 5]
  [5 6 7 9]]

 [[1 2 3 4]
  [2 3 4 5]
  [0 6 9 8]]

 [[1 2 1 4]
  [2 4 4 5]
  [5 6 7 3]]], shape=(3, 3, 4), dtype=int32)


In [ ]:
zeros=tf.zeros((3,4))
print(zeros)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [ ]:
sample=tf.constant([
  [1, 2, 3, 4],
  [2, 4, 4, 5],
  [5, 6, 7, 9]
])
zero_like=tf.zeros_like(sample)
print(zero_like)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [ ]:
ones=tf.ones((3,4))
print(ones)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [ ]:
ones_like=tf.ones_like(sample)
print(ones_like)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [ ]:
filling=tf.fill((3,4),8)
print(filling)

tf.Tensor(
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]], shape=(3, 4), dtype=int32)


In [ ]:
eye_tensor=tf.eye(3)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
